<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE cartes 
[
<!ELEMENT cartes (carte+)>
<!ELEMENT carte (id, nom, prix, couleur, periode, image, 
Activation?, aRetourner?, ptsVictActivation?, ptsPauvretePerdus?,
ptsPauvreteGagnes?, id_EffActiation?>
<!ELEMENT Activation(id_Activation, MontantActivation?, CouleurActivation?)>

<!ELEMENT id (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prix (#PCDATA)>
<!ELEMENT couleur (#PCDATA)>
<!ELEMENT periode (#PCDATA)>
<!ELEMENT image (#PCDATA)>

<!ATTLIST carte aRetourner (true | false) #REQUIRED>
<!ELEMENT ptsVictActivation (#PCDATA)>
<!ELEMENT ptsPauvretePerdus (#PCDATA)>
<!ELEMENT ptsPauvreteGagnes (#PCDATA)>
<!ELEMENT id_EffActiation (#PCDATA)>

<!ELEMENT id_Activation (#PCDATA)>
<!ELEMENT MontantActivation (#PCDATA)>
<!ELEMENT CouleurActivation (#PCDATA)>

]>

<cartes>
	<carte>
		<id>1</id>
		<nom>Pauvres</nom>
		<prix>0</prix>
		<couleur>Gris</couleur>
		<periode>A</periode>
		<image>img</image>
	</carte>
	<carte>
		<id>2</id>
		<nom>Forces de Police</nom>
		<prix>2</prix>
		<couleur>Rose</couleur>
		<periode>B</periode>
		<image>img</image>
		<ptsVictoire>0</ptsVictoire>
		<id_EffActivation>1</id_EffActivation>
		<Activation>
			<id_Activation>
			1
			</id_Activation>
			<MontantActivation>
			3
			</MontnantActivation>
			<CouleurActivation>
			Rose
			</CouleurActivation>
		</Activation>
		<aRetourner>true</aRetourner>
		<ptsVictActivation>2</ptsVictActivation>
		<ptsPauvretePerdus>0</ptsPauvretePerdus>
		<ptsPauvreteGagnes>0</ptsPauvreteGagnes>
	</carte>
	<carte>
		<id>3</id>
		<nom>Pauvres</nom>
		<prix>0</prix>
		<periode>C</periode>
		<couleur>Gris</couleur>
		<image>img</image>
	</carte>
</cartes>